# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!
target 'LimitFree' do
pod 'AFNetworking', '~>2.5.4'
pod 'SDWebImage'
pod 'MBProgressHUD'
pod 'YYModel', '~>0.9.12'
pod 'KVNProgress'
pod 'Masonry'
pod 'MJRefresh'
pod 'FMDB'
pod 'DateTools'
# Xcode 6.x
# pod 'UMengSocial', '4.2.5'
pod 'AVOSCloud'
end
